- name: Installer Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Installer PHP et les modules nécessaires
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - php
    - libapache2-mod-php
    - php-mysql

- name: Activer le module PHP dans Apache
  command: a2enmod php
  notify: Redémarrer Apache
  when: ansible_distribution == "Ubuntu"

- name: Déployer une page PHP de test
  template:
    src: phpinfo.php.j2
    dest: /var/www/html/index.php
    mode: '0644'

- name: S'assurer qu'Apache est démarré et activé au démarrage
  service:
    name: apache2
    state: started
    enabled: yes